//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kuujinbo.ASP.NET.Mvc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kuujinbo.ASP.NET.Mvc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function CheckboxGroupToggler(a) { Object.defineProperty(this, &quot;initError&quot;, { value: &quot;CSS selector for the checkbox group parent DOM element required.&quot; }); Object.defineProperty(this, &quot;containerError&quot;, { value: &quot;checkbox group parent DOM element not found. verify CSS selector is correct&quot; }); Object.defineProperty(this, &quot;buttonUncheckClassList&quot;, { value: &quot;btn btn-sm btn-default&quot; }); Object.defineProperty(this, &quot;buttonCheckClassList&quot;, { value: &quot;btn btn-sm btn-primary checked&quot; }); if (!a || !a.match(/\w+/)) th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CheckboxGroupToggler_min {
            get {
                return ResourceManager.GetString("CheckboxGroupToggler_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&apos;text/css&apos;&gt;
        ///.spin-infinite {
        ///    -webkit-animation: spin-infinite .8s infinite linear;
        ///    -moz-animation: spin-infinite 1s infinite linear;
        ///    -o-animation: spin-infinite 1s infinite linear;
        ///    animation: spin-infinite 1s infinite linear;
        ///}
        ///@-moz-keyframes spin-infinite {
        ///  from {-moz-transform: rotate(0deg);}  
        ///  to {-moz-transform: rotate(360deg);}
        ///}
        ///
        ///@-webkit-keyframes spin-infinite {
        ///  from {-webkit-transform: rotate(0deg);}
        ///  to { -webkit-transform: rotate(360deg);}
        ///}
        ///
        ///@ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Css {
            get {
                return ResourceManager.GetString("Css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&apos;text/css&apos;&gt;
        ///.spin-infinite {
        ///    -webkit-animation: spin-infinite .8s infinite linear;
        ///    -moz-animation: spin-infinite 1s infinite linear;
        ///    -o-animation: spin-infinite 1s infinite linear;
        ///    animation: spin-infinite 1s infinite linear;
        ///}
        ///@-moz-keyframes spin-infinite {
        ///  from {-moz-transform: rotate(0deg);}  
        ///  to {-moz-transform: rotate(360deg);}
        ///}
        ///
        ///@-webkit-keyframes spin-infinite {
        ///  from {-webkit-transform: rotate(0deg);}
        ///  to { -webkit-transform: rotate(360deg);}
        ///}
        ///
        ///@ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Css_min {
            get {
                return ResourceManager.GetString("Css_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function FileUploadField(){Object.defineProperty(this,&quot;maxSizeExceeded&quot;,{value:&quot;Max File Upload Size Exceeded&quot;});this._jQueryUI=&quot;undefined&quot;!==typeof jQuery&amp;&amp;&quot;undefined&quot;!==typeof jQuery.ui&amp;&amp;&quot;function&quot;===typeof jQuery.ui.dialog} FileUploadField.prototype={constructor:FileUploadField,toMB:function(a){return parseFloat((a/Math.pow(1024,Math.floor(Math.log(a)/Math.log(1024)))).toFixed(2))+&quot; MB&quot;},clearUpload:function(a){this.clearUploadUpateDom(a.target)},clearUploadUpateDom:function(a){a.parentNode.parentNode.fi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FileUploadField_min {
            get {
                return ResourceManager.GetString("FileUploadField_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function Xhr(b,a,d){Object.defineProperty(this,&quot;urlError&quot;,{value:&quot;url required.&quot;});Object.defineProperty(this,&quot;doneCallbackError&quot;,{value:&quot;doneCallback required, and must be a function().&quot;});Object.defineProperty(this,&quot;failTitle&quot;,{value:&quot;Unable to Process Request&quot;});Object.defineProperty(this,&quot;defaultFailMessage&quot;,{value:&quot;There was a problem processing your request. Please try again. If the problem continues please contact the application administrators.&quot;});Object.defineProperty(this,&quot;xsrf&quot;,{value:&quot;__RequestV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jQueryAjaxHelper_min {
            get {
                return ResourceManager.GetString("jQueryAjaxHelper_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function jQueryAutoComplete(a,b){Object.defineProperty(this,&quot;jQueryRequiredError&quot;,{value:&quot;jQuery and jQuery UI libraries required.&quot;});Object.defineProperty(this,&quot;searchInputError&quot;,{value:&quot;Search &lt;input&gt; selector missing or DOM element could not be found.&quot;});Object.defineProperty(this,&quot;selectCallbackError&quot;,{value:&quot;selectCallback required and **MUST** be a JavaScript function with *EXACT** signature:\n\nfunction (event, ui) {}&quot;});Object.defineProperty(this,&quot;resultElementError&quot;,{value:&quot;autocomplete results DOM [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jQueryAutoComplete_min {
            get {
                return ResourceManager.GetString("jQueryAutoComplete_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function SessionTerminator(){Object.defineProperty(this,&quot;initError&quot;,{value:&quot;logoutUrl required&quot;});Object.defineProperty(this,&quot;adminTimeout&quot;,{value:600});Object.defineProperty(this,&quot;maxTimeout&quot;,{value:900});this._jQueryUI=&quot;undefined&quot;!==typeof jQuery&amp;&amp;&quot;undefined&quot;!==typeof jQuery.ui&amp;&amp;&quot;function&quot;===typeof jQuery.ui.dialog;this._timeoutID=0;this._idleTimeout=this.adminTimeout;this._logoutUrl=&quot;&quot;} SessionTerminator.prototype={constructor:SessionTerminator,init:function(a,b){if(!b||!b.match(/[\/\w]+/))throw this.ini [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SessionTerminator_min {
            get {
                return ResourceManager.GetString("SessionTerminator_min", resourceCulture);
            }
        }
    }
}
