//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kuujinbo.ASP.NET.Mvc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kuujinbo.ASP.NET.Mvc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function CheckboxGroupToggler(groupSelector) {
        ///    Object.defineProperty(this, &apos;initError&apos;, {
        ///        value: &apos;CSS selector for the checkbox group parent DOM element required.&apos;
        ///    });
        ///
        ///    Object.defineProperty(this, &apos;containerError&apos;, {
        ///        value: &apos;checkbox group parent DOM element not found. verify CSS selector is correct&apos;
        ///    });
        ///
        ///    Object.defineProperty(this, &apos;buttonUncheckClassList&apos;, {
        ///        value: &apos;btn btn-default&apos;
        ///    });
        ///    Object.defineProperty(this, &apos;buttonCheckClassList&apos;, {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CheckboxGroupToggler {
            get {
                return ResourceManager.GetString("CheckboxGroupToggler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function FileUploadField() { }
        ///
        ///FileUploadField.prototype = {
        ///    constructor: FileUploadField,
        ///    toMB: function(sizeInBytes) {
        ///        var multiplier = 1024;
        ///        var i = Math.floor(Math.log(sizeInBytes) / Math.log(multiplier))
        ///        return parseFloat((sizeInBytes / Math.pow(multiplier, i)).toFixed(2)) + &quot; MB&quot;;
        ///    },
        ///    clearUpload: function(e) {
        ///        this.clearUploadUpateDom(e.target);
        ///    },
        ///    clearUploadUpateDom: function(button) {
        ///        button.parentNode.parentNode.firstEle [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FileUploadField {
            get {
                return ResourceManager.GetString("FileUploadField", resourceCulture);
            }
        }
    }
}
